### PR TITLE
Tiny array gadget fix

### PR DESCRIPTION
**Pull request by mitschabaude**
Single-letter fix :D For a bug that hit me when doing https://github.com/zksecurity/mina-credentials/pull/46

### CODE REVIEW

**Review by boray — APPROVED** [review]

**Comment by mitschabaude** [comment]
thanks @boray - can you run CI please?

**Comment by mitschabaude** [comment]
I don't think this needs a changelog - wdyt @boray? you can add the no-changelog label if you agree

**Comment by boray** [comment]
> I don't think this needs a changelog - wdyt @boray? you can add the no-changelog label if you agree

I don't think there is any user-facing change so we can label no-changelog. Do you have any idea why benchmark fails?

**Comment by Trivo25** [comment]
If it fixes a bug that a user can encounter it warrants a changelog imo!

**Comment by 45930** [comment]
@mitschabaude what is the error case that this fixes?

**Comment by mitschabaude** [comment]
> @mitschabaude what is the error case that this fixes?

it throws an error in a place no error is wanted (witness generator). On an out of bounds array access, the gadget is supposed to fail gracefully and return an unconstrained value.

(If you ask yourself why this is useful: It can be useful when you're in a "dummy" situation already and don't care about the return value. This sort of stuff often happens when you do dynamic reasoning in a static-sized circuit: You'll end up doing superfluous operations, but those aren't supposed to crash. For me it happened here: https://github.com/zksecurity/mina-credentials/pull/46/files#diff-b368b5466f745e5f81526d49eaf016583efcf8c48efefd8276db224cdd9108d6R381-R385)

**Comment by mitschabaude** [comment]
Pushed a changelog!

**Comment by mitschabaude** [comment]
@Trivo25 @45930 now with the changelog I need o1js-admin review!

**Comment by mitschabaude** [comment]
> Do you have any idea why benchmark fails?

Btw, benchmark always fails on PRs from forks. I don't know why (but it's also not a required CI job and doesn't matter)

**Pull request merged**
