### PR TITLE
Updated assert* to require* for rest pending precondition apis. #1247

### PR DESCRIPTION
**Pull request by LuffySama-Dev**
Hi @mitschabaude ,

Creating this pull request for pending updates in precondition.ts and for the test file.
Can you please help to review and let me know if any changes are required ?

The test cases are passing : https://github.com/o1-labs/o1js/issues/1247#issuecomment-1823048183

Thank You 😃

### CODE REVIEW

**Review by mitschabaude — APPROVED** [review]
Nice!

**Comment by mitschabaude** [comment]
Could you add some lines to the changelog? under the same bullet point you already started?

**Comment by Saurabhpatil-dev** [comment]
Yes sure, Let me add it in sometime. 🙌

**Comment by Saurabhpatil-dev** [comment]
Hi @mitschabaude ,

Added in the bullet points in Changelog file.
Can you please help to review ? 

Thank You 😃

**Review by mitschabaude — APPROVED** [review]

**Pull request merged**
