### PR TITLE
Rename files to follow convention

### PR DESCRIPTION
**Pull request by mitschabaude**
closes https://github.com/o1-labs/o1js/issues/1429

bindings: https://github.com/o1-labs/o1js-bindings/pull/242

### CODE REVIEW

**Comment by barriebyron** [comment]
hi @shimkiv  do we want to update the reference docs?
the links still work, since they are permalink to a specific place in the code on a specific branch, however, it seems odd that the docs no longer match the actual filenames
for example 
https://docs.minaprotocol.com/zkapps/o1js-reference/classes/Token#defined-in

**Comment by shimkiv** [comment]
Yes @barriebyron, I think docs should reflect these changes.

**Comment by barriebyron** [comment]
the docs style guide wiki describes the auto-generated docs https://github.com/o1-labs/docs2/wiki/o1js-Reference, but I wonder if this process has been updated, I seem to recall that @MartinMinkov improved this process in https://github.com/o1-labs/o1js/pull/1203

**Comment by barriebyron** [comment]
We run the action to update the auto-generated docs. @MartinMinkov  taught me how and now we have the steps documented https://github.com/o1-labs/docs2/wiki/o1js-Reference

**Pull request merged**
