### PR TITLE
Update bindings

### PR DESCRIPTION
**Pull request by L-as**
Notably includes https://github.com/o1-labs/snarkyjs-bindings/pull/63

### CODE REVIEW

**Comment by mitschabaude** [comment]
look like you have to merge `main` in the bindings PR

**Comment by L-as** [comment]
Do I need to declare the function in some TS file?

**Comment by mitschabaude** [comment]
> Do I need to declare the function in some TS file?

No that's not it, what CI shows is a runtime error

**Comment by mitschabaude** [comment]
You need to push updatd artifacts created by `npm run bindings`

**Comment by mitschabaude** [comment]
Do you still want to land this @L-as? The tests don't work, I'm pretty sure that's just because you didn't check our the bindings submodule at the latest commit of the bindings PR

**Comment by L-as** [comment]
@mitschabaude Sorry for the very late response, but I don't understand why it fails honestly, neither do I understand your hypothesis, because I merely advanced the commit once to include the new functions. I looked at the error when I first pushed the commit and mentally made a note to look at it again, and at that time I assumed it was because I was missing something somewhere to properly export the function, though it works locally (under different circumstances). I wouldn't be so sure it's not buggy but if you believe it isn't then :shrug: .

**Comment by mitschabaude** [comment]
Do you still want to land this @L-as? The tests don't work, I'm pretty sure that's just because you didn't check our the bindings submodule at the latest commit of the bindings PR

> @mitschabaude Sorry for the very late response, but I don't understand why it fails honestly, neither do I understand your hypothesis

@L-as on this PR, if you click on "Files changed", then you see that in the bindings submodule, nothing in the `/compiled` folder changed. This means you don't update the compiled bindings. But snarkyjs CI needs those, therefore the tests here fail.

So, to land this PR, do the following:
```sh
# you are in /snarkyjs
# build updated bindings
npm run bindings

# push those to the bindings PR
cd src/bindings
git add compiled
git add MINA_COMMIT
git commit -m "update bindings"
git push

# update snarkyjs PR
cd ../..
git add src/bindings
git commit -m "bindings"
git push
```

**Comment by L-as** [comment]
I will get back to this

**Comment by Trivo25** [comment]
stale

**Pull request closed without merging**
